name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  from:
    description: "The scope to replace"
    required: true
  to:
    description: "The new scope"
    required: true
  version:
    description: "Version to use with the aliases"
    required: false
    default: "*"
  directories_to_rescope:
    description: "Directories to rescope with an alias"
    required: false
    default: "./"
  pre_publish_commands:
    description: "Commands to run before publishing"
    required: false
    default: |
      npm install
      npm run build
  dependency_types:
    description: "Dependency types to rescope"
    required: false
    default: |
      dependencies
      devDependencies
      peerDependencies
      optionalDependencies
  directories_to_publish:
    description: "Directories to publish"
    required: false
    default: "./"
  publish_flags:
    description: "Flags to pass to the publish command"
    required: false
    default: ""


# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
